version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27018:27017
    networks:
      - my-network

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - my-network
    environment:
      - MONGODB_HOSTNAME=mongodb
      - WATCHFILES_FORCE_POLLING=true

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
